# Check the documentation for more information about the configuration file.
# Link: https://github.com/Slimefun-Addon-Community/HeadLimiter#readme
block-limits:
  cargo:
    items-amount: 25
    items:
      - CARGO_NODE_INPUT
      - CARGO_NODE_OUTPUT
      - CARGO_NODE_OUTPUT_ADVANCED
      - CARGO_NODE
      - CARGO_MANAGER
    permission-amount:
      example_1: 50
      example_2: 100
      example_3: 150
